version: '3'
services:
    transact1:
        # container_name: TransactionServer
        build: ./
        ports:
            - "3000"
        networks:
            - my-network
        environment:
            - NEW_RELIC_LICENSE_KEY=cfc19fda054a34427329a409ec96bb8eFFFFNRAL
            - NEW_RELIC_APP_NAME="DayTradingSystem"
            - PORT=3000
        depends_on:
            - mongo
            - redis
        restart: always
    transact2:
        # container_name: TransactionServer
        build: ./
        ports:
            - "3000"
        networks:
            - my-network
        environment:
            - NEW_RELIC_LICENSE_KEY=cfc19fda054a34427329a409ec96bb8eFFFFNRAL
            - NEW_RELIC_APP_NAME="DayTradingSystem"
            - PORT=3000
        depends_on:
            - mongo
            - redis
        restart: always
    transact3:
        # container_name: TransactionServer
        build: ./
        ports:
            - "3000"
        networks:
            - my-network
        environment:
            - NEW_RELIC_LICENSE_KEY=cfc19fda054a34427329a409ec96bb8eFFFFNRAL
            - NEW_RELIC_APP_NAME="DayTradingSystem"
            - PORT=3000
        depends_on:
            - mongo
            - redis
        restart: always
    mongo:
        container_name: DBContainer
        volumes:
            - 'mongo-data:/data/db'
        image: 'mongo:latest'
        ports:
            - 27017:27017
        networks:
            - my-network
    redis:
        container_name: RedisContainer
        image: 'redis:latest'
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
        networks:
            - my-network
    nginx:
        build: ../nginx/
        depends_on:
            - transact1
            - transact2
            - transact3
        ports:
            - 80:80
        networks:
            - my-network
        restart: always
volumes:
    mongo-data:
    redis_data:
networks:
  my-network:

#if these are seperated, they will no longer exist on the same network, and will be unable to talk
#if you want to bust up this file, you've been warned
