version: '3'
services:
    transact:
        container_name: TransactionServer
        build: ./
        ports:
            - 3000:3000
        environment:
            - NEW_RELIC_LICENSE_KEY=cfc19fda054a34427329a409ec96bb8eFFFFNRAL
            - NEW_RELIC_APP_NAME="DayTradingSystem"
        depends_on:
            - mongo
            - redis
    mongo:
        container_name: DBContainer
        volumes:
            - 'mongo-data:/data/db'
        image: 'mongo:latest'
        ports:
            - 27017:27017
    redis:
        container_name: RedisContainer
        image: 'redis:latest'
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - 6379:6379
volumes:
    mongo-data:
    redis_data:

#if these are seperated, they will no longer exist on the same network, and will be unable to talk
#if you want to bust up this file, you've been warned
